#!/bin/bash
#SBATCH --job-name=ME
#SBATCH --time=00:10:00
#SBATCH --constraint="2.60GHz"
#SBATCH --partition=iric
#SBATCH --qos=iric
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1

##after doing a pip install --user mpi4py

ml python/2.7.5

echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "^^^^^^^start: `date`"
srun --ntasks=1 --cpus-per-task=1 python ME_forward.py $1
echo "^^^^^^^end: `date`"
